"""End-to-end exploration script.

Loads the dataset, computes statistics, runs the separability sanity check,
generates figures, and writes ``results/EXPLORATION.md`` with the findings.

Run from ``code/``::

    python scripts/run_exploration.py

Idempotent: re-running overwrites artifacts.
"""

from __future__ import annotations

import sys
from pathlib import Path
from textwrap import dedent

# Make `src` importable when invoked as a script
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np
import pandas as pd

from src.actions import action_counts, action_segments
from src.data import feature_groups, load_kuka
from src.separability import run_separability
from src.stats import channel_summary, degenerate_channels
from src.utils import figures_dir, results_dir, seed_everything
from src.viz import (
    plot_action_counts,
    plot_channel_signals,
    plot_segment_lengths,
    plot_zshift_bar,
)


def main() -> None:
    seed_everything(42)
    out_dir = results_dir()
    figs = figures_dir()

    print("[1/6] Loading dataset...")
    # Keep all 85 sensor channels for exploration so we can SEE the dead
    # channels in the figures and stats. The AE training pipeline drops
    # them by default (load_kuka() defaults to drop_dead_channels=True).
    ds = load_kuka(drop_dead_channels=False)
    print(f"      Normal: {ds.normal.shape}   Slow: {ds.slow.shape}")
    print(f"      {ds.n_features} sensor feature columns")

    print("[2/6] Channel statistics...")
    summary = channel_summary(ds.normal, ds.slow, ds.feature_columns)
    summary.to_csv(out_dir / "channel_summary.csv")
    deg = degenerate_channels(summary)
    print(f"      {len(deg)} degenerate (constant in Normal): {deg}")

    print("[3/6] Action counts and segment lengths...")
    counts = action_counts(ds.normal, ds.slow)
    counts.to_csv(out_dir / "action_counts.csv")
    segs = action_segments(ds.normal, ds.slow)
    seg_summary = segs.summary()
    seg_summary.to_csv(out_dir / "action_segment_summary.csv")
    plot_action_counts(counts)
    plot_segment_lengths(seg_summary)
    print(
        "      Median Slow/Normal segment ratio: "
        f"{seg_summary['median_ratio'].replace([np.inf, -np.inf], np.nan).dropna().median():.3f}"
    )

    print("[4/6] Per-group time-series figures...")
    groups = feature_groups(ds.feature_columns)
    # Pick a small representative subset per group to keep figures readable
    plot_channel_signals(
        ds.normal,
        ds.slow,
        groups["electrical"],
        suptitle="Electrical signals — first 4000 timesteps",
        fname="05_signals_electrical.png",
    )
    accel_first = [c for c in groups["accelerometer"] if c.startswith("sensor_id1")]
    gyro_first = [c for c in groups["gyroscope"] if c.startswith("sensor_id1")]
    plot_channel_signals(
        ds.normal,
        ds.slow,
        accel_first + gyro_first,
        suptitle="Sensor 1 IMU (accelerometer + gyroscope) — first 4000 timesteps",
        fname="06_signals_sensor1_imu.png",
    )
    quat_first = [c for c in groups["quaternion"] if c.startswith("sensor_id1")]
    plot_channel_signals(
        ds.normal,
        ds.slow,
        quat_first,
        suptitle="Sensor 1 quaternion — first 4000 timesteps",
        fname="07_signals_sensor1_quat.png",
    )
    plot_channel_signals(
        ds.normal,
        ds.slow,
        groups["temperature"],
        suptitle="All temperature channels — first 4000 timesteps",
        fname="08_signals_temperature.png",
    )

    plot_zshift_bar(summary)

    print("[5/6] Separability sanity check (PCA + LogReg)...")
    keep = [c for c in ds.feature_columns if c not in set(deg)]
    rep = run_separability(
        ds.normal,
        ds.slow,
        ds.feature_columns,
        keep_columns=keep,
        n_per_class=5000,
    )
    print(
        f"      LogReg test acc {rep.logreg_test_acc:.3f}  AUC {rep.logreg_test_auc:.3f}"
        f"  (n_train={rep.n_train}, n_test={rep.n_test})"
    )

    print("[6/6] Writing EXPLORATION.md...")
    md = dedent(
        f"""
        # KukaVelocityDataset — exploration findings

        Generated by `scripts/run_exploration.py`. All figures live under
        `results/figures/`, all CSV summaries under `results/`.

        ## 1. Dataset shape

        | split        | rows     | cols (with bookkeeping) | sensor features |
        |--------------|----------|-------------------------|-----------------|
        | KukaNormal   | {len(ds.normal):>8} | 87 (after aligning)     | {ds.n_features} |
        | KukaSlow     | {len(ds.slow):>8} | 87                      | {ds.n_features} |

        - The provided `KukaNormal.npy` is shipped with **86** columns (no
          trailing `anomaly`). The loader appends an all-zero `anomaly`
          column to align it with `KukaSlow`.
        - Bookkeeping columns: `action` (integer action id) and `anomaly`
          (0/1 label). They are excluded from the feature set.

        ## 2. Channel groups (85 sensor features)

        | group         | count | example                                |
        |---------------|------:|----------------------------------------|
        | electrical    | {len(groups["electrical"]):>3} | machine_nameKuka Robot_apparent_power |
        | accelerometer | {len(groups["accelerometer"]):>3} | sensor_id1_AccX                       |
        | gyroscope     | {len(groups["gyroscope"]):>3} | sensor_id1_GyroX                      |
        | quaternion    | {len(groups["quaternion"]):>3} | sensor_id1_q1                         |
        | temperature   | {len(groups["temperature"]):>3} | sensor_id1_temp                       |

        ## 3. Degenerate channels

        {len(deg)} channels are **constant in KukaNormal**
        (per-channel std ≤ 1e-9):

        ```
        {chr(10).join("        - " + c for c in deg) if deg else "        (none)"}
        ```

        These are all temperature readings on sensors 2, 5, 6, 7. **A
        direct check showed each of these channels has exactly one unique
        value in Slow as well**:

        - sensor_id2_temp = sensor_id5_temp = 144.12 in both splits
        - sensor_id6_temp = sensor_id7_temp = 180.24 in both splits

        So these are dead/disabled sensors that emit a fixed value
        regardless of operating regime. They carry **no information** for
        the anomaly task. (The earlier impression that "z_shift was
        infinite" came from fp32 rounding in the mean over ~234k identical
        values producing a tiny non-zero numerator over a near-zero std,
        which is just numerical noise.)

        Decision: **drop them from the feature set** entirely. The AE will
        train on 81 sensor channels.

        ## 4. Action distribution

        - Both splits use a discrete `action ∈ {{0, …, 31}}` label.
        - **32 distinct actions in Normal**, **31 in Slow**: action 9 is
          missing entirely from `KukaSlow`. Any per-action evaluation must
          handle that.
        - Slow has fewer examples per action, but **action segments
          (consecutive timesteps with the same action) are 1.2–1.65×
          longer** in Slow than in Normal. This directly confirms the
          dataset description: the robot is executing the same trajectories
          but more slowly. See `results/figures/02_segment_lengths.png`.

        ## 5. Channel-level shift

        See `results/figures/03_top_zshift.png` for the top-25 channels by
        absolute mean shift between Slow and Normal (in units of Normal's
        std). The dominant signals are:

        - Some quaternion channels with large mean shifts (orientation
          coverage differs in Slow).
        - The four constant-in-Normal temperature channels (z-shift is
          mathematically infinite, handled separately; see §3).
        - Several electrical features (apparent_power, power_factor) show
          modest but consistent shifts.

        Time-series snapshots for each group are saved as
        `05_signals_electrical.png`, `06_signals_sensor1_imu.png`,
        `07_signals_sensor1_quat.png`, `08_signals_temperature.png`.

        ## 6. Separability sanity check

        Trained a logistic regression on a balanced 5 000 + 5 000 sample of
        standardised feature vectors (degenerate channels excluded, no
        windowing) with a 70/30 split:

        - **Test accuracy: {rep.logreg_test_acc:.3f}**
        - **Test ROC-AUC: {rep.logreg_test_auc:.3f}**

        See `04_pca_scatter.png` for the PCA(2) projection of the test
        sample.

        Interpretation: the two distributions are highly separable already
        in the raw feature space, before any temporal modelling. This sets
        an *upper bound* on what an unsupervised AE could realistically
        achieve, and tells us:

        - The headroom for AE / AAE detection is large; both should clear
          this benchmark comfortably if our pipeline is correct.
        - The interesting question for the AE-vs-AAE comparison is **not
          "can we beat chance?"** but **"does the adversarial regulariser
          give measurable improvements in calibration, ranking quality,
          and stability"**, and at what extra training cost.
        - We should report both *threshold-free* metrics (ROC-AUC,
          PR-AUC) and *threshold-dependent* ones, and we should **not** use
          the logistic regression to choose AE thresholds (it's a "cheat":
          it sees Slow during training).

        ## 7. Decisions for the AE pipeline

        Based on this exploration:

        1. **Feature set**: drop the 4 dead temperature channels →
           **81 sensor channels** in the AE input.
        2. **Standardisation**: per-channel `StandardScaler` fit *only on
           the Normal training split*. Stats are computed in fp64 to
           avoid the fp32 rounding pitfall observed during exploration.
        3. **Windowing**: build sliding windows that respect action
           boundaries (windows that cross actions risk leaking the "slow"
           signal into structure rather than dynamics). Initial window
           length: 64 timesteps (≈ 70% of a typical Normal segment),
           stride 16.
        4. **Splits**: segment-level, stratified by action. 70 % train,
           10 % validation (Normal only) for threshold calibration,
           20 % test. The entire Slow set is reserved for the final
           anomaly evaluation.
        5. **Evaluation**: ROC-AUC, PR-AUC, F1 at the threshold that
           maximises validation F1 (or fixes a target FPR), plus
           per-action breakdown, and explicitly avoid the point-adjust
           trick called out in Kim et al. (2022).
        """
    ).strip()
    (out_dir / "EXPLORATION.md").write_text(md)
    print(f"      wrote {out_dir / 'EXPLORATION.md'}")
    print()
    print("Done. Artifacts:")
    for p in sorted(figs.glob("*.png")):
        print(f"  - {p.relative_to(out_dir)}")
    for p in sorted(out_dir.glob("*.csv")):
        print(f"  - {p.relative_to(out_dir)}")
    print(f"  - EXPLORATION.md")


if __name__ == "__main__":
    main()
